In [2]:
%timeit L = [n**2 for n in range(1000)]

313 µs ± 7.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%%timeit
L = []
for n in range(1000):
    L.append(n**2)

424 µs ± 57.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
import numpy as np

In [8]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 20, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.random.random((3,3))

array([[0.82256855, 0.50386435, 0.56192781],
       [0.56311106, 0.29645833, 0.93844508],
       [0.61278166, 0.67908203, 0.31384612]])

In [27]:
np.random.normal(0,1,(3,3))

array([[ 0.79025244,  1.0083221 , -0.17312476],
       [ 0.23854017, -0.20754465,  0.26113704],
       [ 1.7488248 , -0.41424474,  0.09008811]])

In [37]:
np.random.randint(0,10,(3,3))

array([[3, 3, 0],
       [7, 1, 7],
       [1, 8, 8]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.empty(3)

array([1., 1., 1.])

In [41]:
np.random.seed(0)

In [42]:
x1 = np.random.randint(10, size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [43]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2]],

       [[4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0],
        [2, 7, 2, 9, 2],
        [3, 3, 2, 3, 4]],

       [[1, 2, 9, 1, 4],
        [6, 8, 2, 3, 0],
        [0, 6, 0, 6, 3],
        [3, 8, 8, 8, 2]]])

In [49]:
for index, i in enumerate([x1,x2,x3]):
    print(f'x{index} ndim: {i.ndim}\nx{index} shape: {i.shape}\nx{index} size: {i.size}')

x0 ndim: 1
x0 shape: (6,)
x0 size: 6
x1 ndim: 2
x1 shape: (3, 4)
x1 size: 12
x2 ndim: 3
x2 shape: (3, 4, 5)
x2 size: 60


In [50]:
print(x3.dtype)

int32


In [51]:
x2[0,0]

3

In [53]:
x2[:,-1]

array([4, 8, 7])

In [54]:
x3[0,0]

array([4, 3, 4, 4, 8])

In [56]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[:5]

array([0, 1, 2, 3, 4])

In [60]:
x[5:]

array([5, 6, 7, 8, 9])

In [61]:
x[4:7]

array([4, 5, 6])

In [62]:
x[::2]

array([0, 2, 4, 6, 8])

In [68]:
x[1::2]

array([1, 3, 5, 7, 9])

In [69]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [70]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [71]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [72]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [73]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [74]:
x2[::-1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [75]:
x2[:,::-1]

array([[4, 2, 5, 3],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [77]:
#np subarrays return views not copies, modifications to views alter original array:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [78]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [79]:
x2_sub[0,0]=99

In [80]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [81]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [82]:
x2_sub_copy = x2[:2, :2].copy()

In [83]:
x2_sub_copy[0,0] = 42

Reshaping arrays

In [7]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [12]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [13]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [15]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

Concatenation and splitting

In [16]:
x = np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [17]:
z = [99,99,99]

In [18]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [20]:
grid = np.array([[1,2,3],
               [4,5,6]])

In [22]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [26]:
x=np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

#vertically stack arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [30]:
#horizontally stack arrays
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [31]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3= np.split(x,[3,5]) # N splits -> N+1 subarrays
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [32]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
upper,lower=np.vsplit(grid,[2])
print(upper,lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [35]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


computation on np arrays

In [36]:
np.random.seed(0)

In [37]:
def compute_reciprocals(values):
    output=np.empty(len(values))
    for index, i in enumerate(values):
        output[index] = 1.0/i
    return output

In [39]:
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [41]:
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocals(big_array)

5.24 s ± 217 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [44]:
%timeit 1.0/big_array

6.97 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [48]:
x = np.arange(9).reshape(3,3)
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [52]:
x = np.arange(4)
print('x     =',x)
print('x + 5 =',x+5)
print('x - 5 = ',x-5)
print('x * 2 =',x*2)
print('x / 2 =', x/2)
print('x // 2 =', x//2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [57]:
print(-x, x**2, x%2)

[ 0 -1 -2 -3] [0 1 4 9] [0 1 0 1]


In [58]:
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [59]:
np.add(x,2) #long hand of x+2

array([2, 3, 4, 5])

In [60]:
#np.add == x+1
#np.subtract == x-1
#np.negative == -x
#np.multiply == x*1
#np.divide == x/1
#np.floor_divide == x//1
#np.power == x**1
#np.mod == x%1

In [62]:
x = np.array([-2,-1,0,1,2])

In [63]:
abs(x)

array([2, 1, 0, 1, 2])

In [64]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [65]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [67]:
x = np.array([3-4j, 4-3j, 2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [69]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [70]:
print(theta, np.sin(theta), np.cos(theta), np.tan(theta))

[0.         1.57079633 3.14159265] [0.0000000e+00 1.0000000e+00 1.2246468e-16] [ 1.000000e+00  6.123234e-17 -1.000000e+00] [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [71]:
x = [-1,0,1]

In [72]:
print(x, np.arcsin(x), np.arccos(x), np.arctan(x))

[-1, 0, 1] [-1.57079633  0.          1.57079633] [3.14159265 1.57079633 0.        ] [-0.78539816  0.          0.78539816]


In [73]:
x=[1,2,3]
print(x,np.exp(x), np.exp2(x), np.power(3,x))

[1, 2, 3] [ 2.71828183  7.3890561  20.08553692] [2. 4. 8.] [ 3  9 27]


In [75]:
x=[1,2,4,10]
print(x, np.log(x), np.log2(x), np.log10(x))

[1, 2, 4, 10] [0.         0.69314718 1.38629436 2.30258509] [0.         1.         2.         3.32192809] [0.         0.30103    0.60205999 1.        ]


In [77]:
x=[0,0.001, 0.1, 0.1]
print(np.expm1(x), np.log1p(x))

[0.         0.0010005  0.10517092 0.10517092] [0.         0.0009995  0.09531018 0.09531018]


In [81]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10, out=y)

array([ 0., 10., 20., 30., 40.])

In [83]:
y= np.multiply(x,10)

In [85]:
y= np.zeros(10)
np.power(2, x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [87]:
y[::2] = 2**x # creates temporary array, above better for larger arrays
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [90]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [91]:
np.multiply.reduce(x)

120

In [92]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [95]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [98]:
L = np.random.random(100)
sum(L)

50.54366386299823

In [99]:
np.sum(L)

50.543663862998244

In [100]:
big_array=np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

43.2 ms ± 2.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
107 µs ± 4.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [102]:
min(big_array), max(big_array)

(3.129521215949893e-06, 0.999995293174921)

In [103]:
np.min(big_array), np.max(big_array)

(3.129521215949893e-06, 0.999995293174921)

In [104]:
big_array.sum(), big_array.max(), big_array.min()

(49860.52994034515, 0.999995293174921, 3.129521215949893e-06)

In [106]:
M = np.random.random((3,4))
M

array([[0.31757751, 0.67206083, 0.31315193, 0.59404038],
       [0.25572477, 0.28918859, 0.11855864, 0.24491079],
       [0.508196  , 0.14591668, 0.77464006, 0.37757124]])

In [107]:
M.sum()

4.61153743102815

In [108]:
M.min(axis=0)

array([0.25572477, 0.14591668, 0.11855864, 0.24491079])

In [110]:
M.max(axis=1)

array([0.67206083, 0.28918859, 0.77464006])

True