In [2]:
%timeit L = [n**2 for n in range(1000)]

313 µs ± 7.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%%timeit
L = []
for n in range(1000):
    L.append(n**2)

424 µs ± 57.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
import numpy as np

In [8]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 20, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.random.random((3,3))

array([[0.82256855, 0.50386435, 0.56192781],
       [0.56311106, 0.29645833, 0.93844508],
       [0.61278166, 0.67908203, 0.31384612]])

In [27]:
np.random.normal(0,1,(3,3))

array([[ 0.79025244,  1.0083221 , -0.17312476],
       [ 0.23854017, -0.20754465,  0.26113704],
       [ 1.7488248 , -0.41424474,  0.09008811]])

In [37]:
np.random.randint(0,10,(3,3))

array([[3, 3, 0],
       [7, 1, 7],
       [1, 8, 8]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.empty(3)

array([1., 1., 1.])

In [41]:
np.random.seed(0)

In [42]:
x1 = np.random.randint(10, size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [43]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2]],

       [[4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0],
        [2, 7, 2, 9, 2],
        [3, 3, 2, 3, 4]],

       [[1, 2, 9, 1, 4],
        [6, 8, 2, 3, 0],
        [0, 6, 0, 6, 3],
        [3, 8, 8, 8, 2]]])

In [49]:
for index, i in enumerate([x1,x2,x3]):
    print(f'x{index} ndim: {i.ndim}\nx{index} shape: {i.shape}\nx{index} size: {i.size}')

x0 ndim: 1
x0 shape: (6,)
x0 size: 6
x1 ndim: 2
x1 shape: (3, 4)
x1 size: 12
x2 ndim: 3
x2 shape: (3, 4, 5)
x2 size: 60


In [50]:
print(x3.dtype)

int32


In [51]:
x2[0,0]

3

In [53]:
x2[:,-1]

array([4, 8, 7])

In [54]:
x3[0,0]

array([4, 3, 4, 4, 8])

In [56]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[:5]

array([0, 1, 2, 3, 4])

In [60]:
x[5:]

array([5, 6, 7, 8, 9])

In [61]:
x[4:7]

array([4, 5, 6])

In [62]:
x[::2]

array([0, 2, 4, 6, 8])

In [68]:
x[1::2]

array([1, 3, 5, 7, 9])

In [69]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [70]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [71]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [72]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [73]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [74]:
x2[::-1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [75]:
x2[:,::-1]

array([[4, 2, 5, 3],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [77]:
#np subarrays return views not copies, modifications to views alter original array:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [78]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [79]:
x2_sub[0,0]=99

In [80]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [81]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [82]:
x2_sub_copy = x2[:2, :2].copy()

In [83]:
x2_sub_copy[0,0] = 42

In [ ]:
sdf
%debug