In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data['b']

0.5

In [8]:
# series as specialized dict
population_dict = {'California': 38332521,
                  'Texas': 26448193,
                  'New York': 19651127,
                  'Florida': 19552860,
                  'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [9]:
population['California']

38332521

In [10]:
population[0]

38332521

In [11]:
population['California': 'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [12]:
area_dict = {'California': 2345, 'Texas': 27865, 'New York': 6745, 'Florida': 2456, 'Illinois': 9876}
area = pd.Series(area_dict)
area

California     2345
Texas         27865
New York       6745
Florida        2456
Illinois       9876
dtype: int64

In [13]:
states = pd.DataFrame({'population': population, 'area': area})
states

population   area
California    38332521   2345
Texas         26448193  27865
New York      19651127   6745
Florida       19552860   2456
Illinois      12882135   9876

In [14]:
states['area']

California     2345
Texas         27865
New York       6745
Florida        2456
Illinois       9876
Name: area, dtype: int64

In [15]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [16]:
ind[1]

3

In [17]:
ind[1::2]

Int64Index([3, 7], dtype='int64')

In [18]:
ind.size, ind.shape, ind.ndim, ind.dtype

(5, (5,), 1, dtype('int64'))

In [19]:
indA = pd.Index([1,2,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [20]:
indA & indB #intersection

Int64Index([2, 3, 5, 7], dtype='int64')

In [21]:
indA | indB #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

Data Indexing and Selection

In [22]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [23]:
'a' in data

True

In [24]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [26]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [27]:
data['a':'c'] #slicing by explicit index

a    0.25
b    0.50
c    0.75
dtype: float64

In [28]:
data[0:2] #slicing by implicit index

a    0.25
b    0.50
dtype: float64

In [29]:
data[(data>0.3) & (data <0.8)] #masking

b    0.50
c    0.75
dtype: float64

In [30]:
data[['a', 'e']] #fancy indexing

a    0.25
e    1.25
dtype: float64

In [31]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1,3,5,7])
data.loc[3]

0.5

In [32]:
data.loc[1:3]

1    0.25
3    0.50
dtype: float64

In [33]:
data.iloc[1:3] # guiding principle of python code: explicit better than implicit, use loc&iloc over [] when needed

3    0.50
5    0.75
dtype: float64

In [35]:
data = pd.DataFrame({'area': area, 'pop': population})
data

area       pop
California   2345  38332521
Texas       27865  26448193
New York     6745  19651127
Florida      2456  19552860
Illinois     9876  12882135

In [36]:
data['area'] #data.area

California     2345
Texas         27865
New York       6745
Florida        2456
Illinois       9876
Name: area, dtype: int64

In [37]:
data.area is data['area']

True

In [38]:
data.pop is data['pop'] #DataFrame has pop() method

False

In [40]:
data['density'] = data['pop']/data['area']
data

area       pop       density
California   2345  38332521  16346.490832
Texas       27865  26448193    949.154603
New York     6745  19651127   2913.436175
Florida      2456  19552860   7961.262215
Illinois     9876  12882135   1304.387910

In [46]:
data.values #data as a 2d array

array([[2.34500000e+03, 3.83325210e+07, 1.63464908e+04],
       [2.78650000e+04, 2.64481930e+07, 9.49154603e+02],
       [6.74500000e+03, 1.96511270e+07, 2.91343617e+03],
       [2.45600000e+03, 1.95528600e+07, 7.96126221e+03],
       [9.87600000e+03, 1.28821350e+07, 1.30438791e+03]])

In [42]:
data.T

California         Texas      New York       Florida      Illinois
area     2.345000e+03  2.786500e+04  6.745000e+03  2.456000e+03  9.876000e+03
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  1.634649e+04  9.491546e+02  2.913436e+03  7.961262e+03  1.304388e+03

In [48]:
data.values[0]

array([2.34500000e+03, 3.83325210e+07, 1.63464908e+04])

In [49]:
data.iloc[:3, :2]

area       pop
California   2345  38332521
Texas       27865  26448193
New York     6745  19651127

In [51]:
data.loc[:'New York', :'pop']

area       pop
California   2345  38332521
Texas       27865  26448193
New York     6745  19651127

In [55]:
data.loc[data.density > 1000, ['pop', 'density']]

pop       density
California  38332521  16346.490832
New York    19651127   2913.436175
Florida     19552860   7961.262215
Illinois    12882135   1304.387910

In [66]:
data.loc[data['pop'] > 20000000]

area       pop       density
California   2345  38332521  16346.490832
Texas       27865  26448193    949.154603

In [65]:
data.loc[data.density > 2000]

area       pop       density
California  2345  38332521  16346.490832
New York    6745  19651127   2913.436175
Florida     2456  19552860   7961.262215

operating on data in pandas

In [67]:
# ufunc: index preservation
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [70]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [71]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [72]:
np.sin(df * np.pi/4)

A         B             C             D
0 -1.000000e+00  0.707107 -2.449294e-16  1.000000e+00
1  1.224647e-16  1.000000 -1.000000e+00  1.224647e-16
2 -2.449294e-16 -1.000000  7.071068e-01  7.071068e-01

In [75]:
arr = np.array(df.values)
arr

array([[6, 3, 8, 2],
       [4, 2, 6, 4],
       [8, 6, 1, 3]])

In [76]:
np.sin(arr * np.pi/4)

array([[-1.00000000e+00,  7.07106781e-01, -2.44929360e-16,
         1.00000000e+00],
       [ 1.22464680e-16,  1.00000000e+00, -1.00000000e+00,
         1.22464680e-16],
       [-2.44929360e-16, -1.00000000e+00,  7.07106781e-01,
         7.07106781e-01]])

In [79]:
# index alignment
area = pd.Series({'Alaska':12453, 'Texas': 76543, 'California': 9865394}, name = 'area')
population = pd.Series({'California': 6433256, 'Texas': 596432, 'New York': 194843}, name = 'population')

In [81]:
population/area

Alaska             NaN
California    0.652103
New York           NaN
Texas         7.792117
dtype: float64