In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data['b']

0.5

In [8]:
# series as specialized dict
population_dict = {'California': 38332521,
                  'Texas': 26448193,
                  'New York': 19651127,
                  'Florida': 19552860,
                  'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [9]:
population['California']

38332521

In [10]:
population[0]

38332521

In [11]:
population['California': 'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [12]:
area_dict = {'California': 2345, 'Texas': 27865, 'New York': 6745, 'Florida': 2456, 'Illinois': 9876}
area = pd.Series(area_dict)
area

California     2345
Texas         27865
New York       6745
Florida        2456
Illinois       9876
dtype: int64

In [13]:
states = pd.DataFrame({'population': population, 'area': area})
states

population   area
California    38332521   2345
Texas         26448193  27865
New York      19651127   6745
Florida       19552860   2456
Illinois      12882135   9876

In [14]:
states['area']

California     2345
Texas         27865
New York       6745
Florida        2456
Illinois       9876
Name: area, dtype: int64

In [15]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [16]:
ind[1]

3

In [17]:
ind[1::2]

Int64Index([3, 7], dtype='int64')

In [18]:
ind.size, ind.shape, ind.ndim, ind.dtype

(5, (5,), 1, dtype('int64'))

In [19]:
indA = pd.Index([1,2,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [20]:
indA & indB #intersection

Int64Index([2, 3, 5, 7], dtype='int64')

In [21]:
indA | indB #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

Data Indexing and Selection

In [22]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [23]:
'a' in data

True

In [24]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [26]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [27]:
data['a':'c'] #slicing by explicit index

a    0.25
b    0.50
c    0.75
dtype: float64

In [28]:
data[0:2] #slicing by implicit index

a    0.25
b    0.50
dtype: float64

In [29]:
data[(data>0.3) & (data <0.8)] #masking

b    0.50
c    0.75
dtype: float64

In [30]:
data[['a', 'e']] #fancy indexing

a    0.25
e    1.25
dtype: float64

In [31]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1,3,5,7])
data.loc[3]

0.5

In [32]:
data.loc[1:3]

1    0.25
3    0.50
dtype: float64

In [33]:
data.iloc[1:3] # guiding principle of python code: explicit better than implicit, use loc&iloc over [] when needed

3    0.50
5    0.75
dtype: float64

In [34]:
data = pd.DataFrame({'area': area, 'pop': population})
data

area       pop
California   2345  38332521
Texas       27865  26448193
New York     6745  19651127
Florida      2456  19552860
Illinois     9876  12882135

In [35]:
data['area'] #data.area

California     2345
Texas         27865
New York       6745
Florida        2456
Illinois       9876
Name: area, dtype: int64

In [36]:
data.area is data['area']

True

In [37]:
data.pop is data['pop'] #DataFrame has pop() method

False

In [38]:
data['density'] = data['pop']/data['area']
data

area       pop       density
California   2345  38332521  16346.490832
Texas       27865  26448193    949.154603
New York     6745  19651127   2913.436175
Florida      2456  19552860   7961.262215
Illinois     9876  12882135   1304.387910

In [39]:
data.values #data as a 2d array

array([[2.34500000e+03, 3.83325210e+07, 1.63464908e+04],
       [2.78650000e+04, 2.64481930e+07, 9.49154603e+02],
       [6.74500000e+03, 1.96511270e+07, 2.91343617e+03],
       [2.45600000e+03, 1.95528600e+07, 7.96126221e+03],
       [9.87600000e+03, 1.28821350e+07, 1.30438791e+03]])

In [40]:
data.T

California         Texas      New York       Florida      Illinois
area     2.345000e+03  2.786500e+04  6.745000e+03  2.456000e+03  9.876000e+03
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  1.634649e+04  9.491546e+02  2.913436e+03  7.961262e+03  1.304388e+03

In [41]:
data.values[0]

array([2.34500000e+03, 3.83325210e+07, 1.63464908e+04])

In [42]:
data.iloc[:3, :2]

area       pop
California   2345  38332521
Texas       27865  26448193
New York     6745  19651127

In [43]:
data.loc[:'New York', :'pop']

area       pop
California   2345  38332521
Texas       27865  26448193
New York     6745  19651127

In [44]:
data.loc[data.density > 1000, ['pop', 'density']]

pop       density
California  38332521  16346.490832
New York    19651127   2913.436175
Florida     19552860   7961.262215
Illinois    12882135   1304.387910

In [45]:
data.loc[data['pop'] > 20000000]

area       pop       density
California   2345  38332521  16346.490832
Texas       27865  26448193    949.154603

In [46]:
data.loc[data.density > 2000]

area       pop       density
California  2345  38332521  16346.490832
New York    6745  19651127   2913.436175
Florida     2456  19552860   7961.262215

operating on data in pandas

In [47]:
# ufunc: index preservation
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [48]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [49]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [50]:
np.sin(df * np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [51]:
arr = np.array(df.values)
arr

array([[6, 9, 2, 6],
       [7, 4, 3, 7],
       [7, 2, 5, 4]])

In [52]:
np.sin(arr * np.pi/4)

array([[-1.00000000e+00,  7.07106781e-01,  1.00000000e+00,
        -1.00000000e+00],
       [-7.07106781e-01,  1.22464680e-16,  7.07106781e-01,
        -7.07106781e-01],
       [-7.07106781e-01,  1.00000000e+00, -7.07106781e-01,
         1.22464680e-16]])

In [53]:
# index alignment
area = pd.Series({'Alaska':12453, 'Texas': 76543, 'California': 9865394}, name = 'area')
population = pd.Series({'California': 6433256, 'Texas': 596432, 'New York': 194843}, name = 'population')

In [54]:
population/area

Alaska             NaN
California    0.652103
New York           NaN
Texas         7.792117
dtype: float64

handling missing data

In [55]:
# pandas uses two sentinel values for missing values: None & NaN
vals1 = np.array([1, None, 3, 4])
vals1 # dtype=object computations done at python level

array([1, None, 3, 4], dtype=object)

In [56]:
for dtype in ['object', 'int']:
    print('dtype = ', dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()
    
# computations much quicker on np types than general object type

dtype =  object
75.5 ms ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype =  int
2.41 ms ± 164 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [57]:
#vals1.sum() #errors on aggregating object types

In [58]:
vals2 = np.array([1, np.nan, 3,4])
vals2.dtype

dtype('float64')

In [59]:
1 + np.nan # data 'virus'; turns data to nan when arithmatic

nan

In [60]:
vals2.sum(), vals2.min(), vals2.max() # aggregates well defined, not always useful

(nan, nan, nan)

In [61]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2) # nan specifically a floating point value

(8.0, 1.0, 4.0)

In [62]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [63]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [64]:
x[0] = None
x # upcasts to a floating point type to accommodate NA

0    NaN
1    1.0
dtype: float64

In [65]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [66]:
data.isnull() # returns boolean mask over data

0    False
1     True
2    False
3     True
dtype: bool

In [67]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [68]:
data.dropna()

0        1
2    hello
dtype: object

In [69]:
df = pd.DataFrame([[1, np.nan, 2],
                 [2,3,5],
                 [np.nan, 4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [70]:
df.dropna() # default: drops rows with NA

0    1  2
1  2.0  3.0  5

In [71]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [72]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [73]:
df.dropna(axis='columns', how ='all') # how allows finer control; 'all' drops where all values are NA

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [74]:
df.dropna(axis='rows', thresh =3) # thresh lets you specify min number of non NA values for row/column to be kept

0    1  2   3
1  2.0  3.0  5 NaN

In [75]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [76]:
data.fillna(0) # fill NAs with 0

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [77]:
data.fillna(method='ffill') # forward fill propogates values forward from previous

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [78]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [79]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [80]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

hierarchical indexing

In [82]:
# bad method
index = [('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]
populations = [2453456, 34563423, 23455, 654323456, 2345654, 765432]
pop = pd.Series(populations, index=index)
pop

(California, 2000)      2453456
(California, 2010)     34563423
(New York, 2000)          23455
(New York, 2010)      654323456
(Texas, 2000)           2345654
(Texas, 2010)            765432
dtype: int64

In [83]:
pop[('California', 2000):('Texas', 2000)]

(California, 2000)      2453456
(California, 2010)     34563423
(New York, 2000)          23455
(New York, 2010)      654323456
(Texas, 2000)           2345654
dtype: int64

In [84]:
# messy coding:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)     34563423
(New York, 2010)      654323456
(Texas, 2010)            765432
dtype: int64

In [85]:
# better method
index = pd.MultiIndex.from_tuples(index)

In [86]:
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [87]:
pop = pop.reindex(index)
pop

California  2000      2453456
            2010     34563423
New York    2000        23455
            2010    654323456
Texas       2000      2345654
            2010       765432
dtype: int64

In [88]:
pop[:, 2010]

California     34563423
New York      654323456
Texas            765432
dtype: int64

In [89]:
pop_df = pop.unstack()
pop_df

2000       2010
California  2453456   34563423
New York      23455  654323456
Texas       2345654     765432

In [90]:
pop_df.stack()

California  2000      2453456
            2010     34563423
New York    2000        23455
            2010    654323456
Texas       2000      2345654
            2010       765432
dtype: int64

In [91]:
pop_df = pd.DataFrame({'total': pop, 
                      'under18': [9878, 334564,
                                 15643, 45667,
                                 233567, 98769]})
pop_df

total  under18
California 2000    2453456     9878
           2010   34563423   334564
New York   2000      23455    45643
           2010  654323456    45667
Texas      2000    2345654   233567
           2010     765432    98769

In [92]:
f_u18 = pop_df['under18']/pop_df['total']
f_u18.unstack()

2000      2010
California  0.004026  0.009680
New York    1.945982  0.000070
Texas       0.099574  0.129037

In [93]:
df = pd.DataFrame(np.random.rand(4,2),
                 index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                 columns = ['data1', 'data2'])
df

data1     data2
a 1  0.532198  0.111673
  2  0.857222  0.804953
b 1  0.684582  0.101345
  2  0.223238  0.803982